# Cross toolchain for a 64-bit Raspberry Pi OS target.
set(CMAKE_SYSTEM_NAME Linux)
set(FPRIME_PLATFORM "Linux")
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_SYSTEM_NAME Generic_RaspberryPi)

set(CMAKE_C_COMPILER "aarch64-unknown-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "aarch64-unknown-linux-gnu-g++")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
